[build]
  command = "git clone https://github.com/flutter/flutter.git -b stable --depth 1 && export PATH=`pwd`/flutter/bin:$PATH && flutter doctor && flutter pub get && flutter build web"
  publish = "build/web"
